version: "3.8"

# In the docker compose file, we define some services (containers) to run.
# This will be geared towards production.
services:

  battlebit-community-api:
    image: bb-community-server-api:latest
    build:
      # Specify how to build the image above.
      context: .

    restart: always
    ports:
      - "29294:29294"
